config/routes.rb
# == Route Map
#
#                    Prefix Verb   URI Pattern                                                                              Controller#Action
#              wheels_index GET    /wheels/index(.:format)                                                                  wheels#index
#              frames_index GET    /frames/index(.:format)                                                                  frames#index
#          user_bikes_index GET    /user_bikes/index(.:format)                                                              user_bikes#index
#          new_user_session GET    /users/sign_in(.:format)                                                                 devise/sessions#new
#              user_session POST   /users/sign_in(.:format)                                                                 devise/sessions#create
#      destroy_user_session DELETE /users/sign_out(.:format)                                                                devise/sessions#destroy
#         new_user_password GET    /users/password/new(.:format)                                                            devise/passwords#new
#        edit_user_password GET    /users/password/edit(.:format)                                                           devise/passwords#edit
#             user_password PATCH  /users/password(.:format)                                                                devise/passwords#update
#                           PUT    /users/password(.:format)                                                                devise/passwords#update
#                           POST   /users/password(.:format)                                                                devise/passwords#create
#  cancel_user_registration GET    /users/cancel(.:format)                                                                  devise/registrations#cancel
#     new_user_registration GET    /users/sign_up(.:format)                                                                 devise/registrations#new
#    edit_user_registration GET    /users/edit(.:format)                                                                    devise/registrations#edit
#         user_registration PATCH  /users(.:format)                                                                         devise/registrations#update
#                           PUT    /users(.:format)                                                                         devise/registrations#update
#                           DELETE /users(.:format)                                                                         devise/registrations#destroy
#                           POST   /users(.:format)                                                                         devise/registrations#create
#                      root GET    /                                                                                        bikes#index
#                     bikes GET    /bikes(.:format)                                                                         bikes#index
#                           POST   /bikes(.:format)                                                                         bikes#create
#                  new_bike GET    /bikes/new(.:format)                                                                     bikes#new
#                 edit_bike GET    /bikes/:id/edit(.:format)                                                                bikes#edit
#                      bike GET    /bikes/:id(.:format)                                                                     bikes#show
#                           PATCH  /bikes/:id(.:format)                                                                     bikes#update
#                           PUT    /bikes/:id(.:format)                                                                     bikes#update
#                           DELETE /bikes/:id(.:format)                                                                     bikes#destroy
#                  addframe GET    /user_bikes/addframe(.:format)                                                           user_bikes#addframe
#        rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
# rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#        rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
# update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#      rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do

  resources :chainsets, except: [:edit, :delete, :update, :new, :create]
  post '/rate' => 'rater#create', :as => 'rate'
  get 'wheels/index'
  resources :frames, except: [:new, :create, :update, :edit, :delete]
  get 'user_bikes/index'
  get 'components', to: 'pages#components', as: 'components'
  devise_for :users
  root 'pages#home'
  get 'about', to: 'pages#about', as: 'about'
  resources :bikes
  get 'user_bikes/addframe', to: 'user_bikes#addframe', as: 'addframe'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/bike.rb
# == Schema Information
#
# Table name: bikes
#
#  id          :bigint(8)        not null, primary key
#  name        :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :bigint(8)
#  frame_id    :integer
#  wheel_id    :integer
#  weight      :integer
#  chainset_id :integer
#  brake_id    :bigint(8)
#

# Create default 0 for weight
# Create attribute for price



class Bike < ApplicationRecord
  
  belongs_to :user
  belongs_to :frame, optional: true
  belongs_to :wheel, optional: true
  belongs_to :chainset, optional: true
  belongs_to :brake, optional: true

  accepts_nested_attributes_for :frame
  accepts_nested_attributes_for :wheel
  accepts_nested_attributes_for :chainset

  validates_presence_of :name
  validates_presence_of :wheel
  validates_presence_of :chainset
  validates_presence_of :frame

  ratyrate_rateable "overall"

  def self.update_total(bike)
  	new_weight = bike.frame.weight + bike.wheel.weight + bike.chainset.weight
    bike.update(weight: new_weight)
  end

end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
  
  before_action :get_bike, only: [:edit,:update, :destroy]
 
  
  def index
    @bikes = Bike.all
  end

  def new
    if !user_signed_in?
    
      redirect_to '/users/sign_in'
    else
    	@bike = Bike.new
      @bike = current_user.bikes.build
      @frames = Frame.all
      @wheels = Wheel.all
    end
  end
  def create
    @bike = current_user.bikes.build(bike_params)
    if @bike.save
      Bike.update_total(@bike)
      redirect_to @bike, notice: 'The bike was successfully updated.'
    else 
      render 'new'
    end
  end

  def show
    @bike = Bike.find(params[:id])
  end

  def edit
    @frames = Frame.all
    @wheels = Wheel.all
    @brakes = Brake.all
    @chainsets = Chainset.all
  end

 def update
    respond_to do |format|
      if @bike.update(bike_params)
        Bike.update_total(@bike)
        format.html { redirect_to @bike, notice: 'The bike was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    if @bike.destroy
      redirect_to bikes_path
    end
  end

  private 

    def get_bike
      @bike = Bike.find(params[:id])
      if current_user != @bike.user
        redirect_to root_path
      end
    end

    def bike_params
      params.require(:bike).permit(:name, :description, :user_id, :frame_id, :brake_id, :wheel_id, :chainset_id)
    end

end

app/helpers/bike_helper.rb
module BikeHelper

  def sign_in
    if user_signed_in?
      link_to "Edit user", edit_user_registration_path
      link_to "Add bike", new_bike_path
      link_to "Your bikes", user_bikes_index_path
    end
  end

  def frame
    if @bike.frame 
	 @bike.frame.manufacturer + " " + @bike.frame.name 
    end 
  end

  def wheels
    if @bike.wheel
      @bike.wheel.manufacturer + " " + @bike.wheel.name
    else 
      "get some wheels"
    end
  end

  def new_bike
    if user_signed_in? 
      link_to "New bike", new_bike_path , class: "btn btn-info"
    end
  end

  def edit_bike
    if user_signed_in? 
      link_to "Edit", edit_bike_path(@bike) , class: "btn btn-info"
    end
  end

  def delete_bike
    if user_signed_in? 
      link_to "Delete", bike_path(@bike), method: :delete, class: "btn btn-info"
    end
  end

end

app/views/bikes/_form.html.erb
<%= simple_form_for @bike do |f| %>
  <%= f.input :name %>
  <%= f.input :description, size: "60x12" %>
  <%= f.input :frame_id, collection: Frame.all %>
  <%= f.input :wheel_id, collection: Wheel.all %>
  <%= f.input :chainset_id, collection: Chainset.all %>
  <%= f.input :brake_id, collection: Brake.all %>
  <%= f.button :submit %>
<% end %>

app/views/bikes/_frame_form.html.erb
<%= form_with model: @bike do |f| %>
  
   <%= f.select :frame_id, Frame.all.collect { |p| p.name }, include_blank: true %>
  <%= f.submit "Create" %>
<% end %>

app/views/bikes/edit.html.erb
Bike Builder



<div class="row">
	<div class="col-md-6">
		<h2>Frames</h2>
		<table class="table">
			<tr>
				<th>Manufacturer</th>
				<th>Model</th>
				<th>Bikes</th>
			</tr>
			<% @frames.each do |frame| %>
			<tr>
				<td><%= frame.manufacturer %></td>
				<td><%= frame.name %></td>
				<td><%= frame.bikes.count %></td>
			</tr>
			<% end %>
		</table>

		<h2>Wheels</h2>
		<table class="table">
			<tr>
				<th>Manufacturer</th>
				<th>Model</th>
				<th>Bikes</th>
			</tr>
			<% @wheels.each do |wheel| %>
			<tr>
				<td><%= wheel.manufacturer %></td>
				<td><%= wheel.name %></td>
				<td><%= wheel.bikes.count %></td>
			</tr>
			<% end %>
		</table>
		<h2>Chainsets</h2>
		<table class="table">
			<tr>
				<th>Manufacturer</th>
				<th>Model</th>
				<th>Bikes</th>
			</tr>
			<% @chainsets.each do |chainset| %>
			<tr>
				<td><%= chainset.manufacturer %></td>
				<td><%= chainset.name %></td>
				<td><%= chainset.bikes.count %></td>
			</tr>
			<% end %>
		</table>
		<h2>Brakes</h2>
		<table class="table">
			<tr>
				<th>Manufacturer</th>
				<th>Model</th>
				<th>Bikes</th>
			</tr>
			<% @brakes.each do |brake| %>
			<tr>
				<td><%= brake.manufacturer %></td>
				<td><%= brake.name %></td>
				<td><%= brake.bikes.count %></td>
			</tr>
			<% end %>
		</table>
	</div>
	<div class="col-md-6">
		<%= render 'form' %>
	</div>
</div>

app/views/bikes/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-10 offset-md-1">
			<table class="table">
		<th>
			Name
		</th>
		<th>
			Description
		</th>
		<th>
			Weight(g)
		</th>
		<th>
			Owner
		</th>
		<th>Rating
		</th>
		<% @bikes.each do |bike| %>
		<tr>
			<td><%= link_to bike.name, bike_path(bike)  %></td>
			<td><%= bike.description %>	</td>
			<td><%= bike.weight %></td>
			<td><%= bike.user.name %></td>
			<td><%= rating_for bike, 'overall' %></td>
		</tr>
		<% end %>
	</table>
		</div>
	</div>
</div>
	
	
		

<%= sign_in %>

app/views/bikes/new.html.erb
<h1>Create a new bike</h1>

<div class="row">
	<div class="col-md-6">
		<h2>Frames</h2>
		<table class="table">
			<tr>
				<th>Manufacturer</th>
				<th>Model</th>
				<th>Bikes</th>
			</tr>
			<% @frames.each do |frame| %>
			<tr>
				<td><%= frame.manufacturer %></td>
				<td><%= frame.name %></td>
				<td><%= frame.bikes.count %></td>
			</tr>
			<% end %>
		</table>

		<h2>Wheels</h2>
		<table class="table">
			<tr>
				<th>Manufacturer</th>
				<th>Model</th>
				<th>Bikes</th>
			</tr>
			<% @wheels.each do |wheel| %>
			<tr>
				<td><%= wheel.manufacturer %></td>
				<td><%= wheel.name %></td>
				<td><%= wheel.bikes.count %></td>
			</tr>
			<% end %>
		</table>
	</div>
	<div class="col-md-6">
		<%= render 'form' %>
	</div>
</div>

app/views/bikes/show.html.erb
<h1>Bike: <%= @bike.name %></h1>
<div class="row">
	<div class="col-md-6">
		<p>Description: <%= @bike.description %>
		<br></p>
        <p><%= rating_for @bike, 'overall' %></p>
		<h2>Components</h2>
		<ul>
			<li>Frame: <%= @bike.frame.manufacturer.capitalize %> <%= link_to @bike.frame.name.capitalize, frame_path(@bike.frame) %> | <%= @bike.frame.weight %>g</li>
			<li>Wheels: <%= @bike.wheel.manufacturer.capitalize %> <%= @bike.wheel.name.capitalize %> | <%= @bike.wheel.weight %>g</li>
			<li>Chainset: <%= @bike.chainset.manufacturer.capitalize %> <%= @bike.chainset.name.capitalize %> | <%= @bike.chainset.weight %>g</li>
		</ul>
	</div>
	<div class="col-md-6">
		<p><%= link_to "Kit index", components_path  %> | <%= link_to "Wheel index", wheels_index_path %></p>
		

		

		<h2>Details</h2>
		<ul>
			<li>Belongs to: <%= @bike.user.name.capitalize %></li>
			<li>Weight: <%= @bike.weight %> grams</li>
		</ul>

		<br>

		<h3>Links</h3>
       
		<p> <%= delete_bike %> | <%= edit_bike %> | <%= new_bike %> </p>

		<%= link_to "My Bikes", user_bikes_index_path  %>

		<p><%= link_to "Main Bike index", bikes_path  %></p>
	</div>
</div>